// Gemaakt door scripts/gangpad_poort.py uit Kniv/Logica/Gangpad.swift; niet met de hand aanpassen.
namespace Kniv;

static partial class Gangpad
{
    public static readonly string[] Namen = { "Groente & fruit", "Brood", "Vlees & vis", "Zuivel & eieren", "Kaas & beleg", "Pasta, rijst & blik", "Ontbijt & koffie", "Koek, snoep & chips", "Drinken", "Diepvries", "Verzorging", "Huishouden", "Overig" };

    static readonly string[][] Woorden =
    {
        new string[] { "appel", "appels", "banaan", "bananen", "peer", "sinaasappel", "citroen", "druiven", "aardbeien", "tomaat", "tomaten", "komkommer", "sla", "paprika", "ui", "uien", "knoflook", "wortel", "wortels", "aardappel", "aardappelen", "broccoli", "spinazie", "avocado", "champignons", "courgette", "prei", "groente", "fruit", "kiwi", "mango", "gember", "bloemkool", "peren", "aardbei", "rucola", "sperziebonen", "snijbonen", "boontjes", "kool", "spitskool", "rodekool", "zuurkool", "andijvie", "boerenkool", "radijs", "biet", "bieten", "pompoen", "aubergine", "asperges", "lente-ui", "bosui", "basilicum", "peterselie", "koriander", "munt", "limoen", "meloen", "ananas", "framboos", "frambozen", "blauwe bessen", "bessen", "pruimen", "perzik", "nectarine", "mandarijn", "mandarijnen", "taugé", "maïs aan de kolf" },
        new string[] { "brood", "broodjes", "croissant", "croissants", "stokbrood", "beschuit", "wraps", "pistolets", "bolletjes", "krentenbollen", "afbakbroodjes", "pita", "tortilla", "tortilla's", "naan", "bagels", "toast" },
        new string[] { "kip", "kipfilet", "gehakt", "vlees", "biefstuk", "worst", "worstjes", "spek", "zalm", "vis", "tonijn", "garnalen", "ham", "shoarma", "hamburger", "hamburgers", "schnitzel", "tofu", "vega", "zalmfilet", "kabeljauw", "kipdijen", "drumsticks", "rookworst", "slavink", "speklapjes", "rundvlees", "varkensvlees", "lamsvlees", "spareribs", "kipkerrie", "tempeh" },
        new string[] { "melk", "yoghurt", "kwark", "vla", "boter", "roomboter", "room", "slagroom", "eieren", "ei", "karnemelk", "margarine", "skyr", "crème fraîche", "zure room", "kookroom", "havermelk", "sojamelk", "pudding", "toetjes", "toetje" },
        new string[] { "kaas", "plakjes", "mozzarella", "feta", "hummus", "salami", "smeerkaas", "beleg", "pindakaas", "hagelslag", "jam", "nutella", "chocopasta", "chocoladepasta", "vlokken", "appelstroop", "honing", "leverworst", "filet americain", "kipfilet beleg", "parmezaan", "geitenkaas", "brie", "roomkaas", "boursin" },
        new string[] { "pasta", "spaghetti", "macaroni", "rijst", "noedels", "bloem", "suiker", "olie", "olijfolie", "azijn", "saus", "pastasaus", "tomatenpuree", "bonen", "mais", "blik", "kruiden", "zout", "peper", "bouillon", "soep", "ketchup", "mayonaise", "mosterd", "lasagne", "penne", "tagliatelle", "couscous", "bulgur", "quinoa", "linzen", "kikkererwten", "tomatenblokjes", "passata", "pesto", "sambal", "sojasaus", "kokosmelk", "curry", "taco", "tacos", "bakpoeder", "gist", "paneermeel", "mie", "wokolie", "zonnebloemolie", "frituurolie", "pindasaus", "satésaus", "fritessaus" },
        new string[] { "koffie", "thee", "cruesli", "muesli", "havermout", "cornflakes", "ontbijtkoek", "cacao", "koffiebonen", "koffiepads", "koffiecups", "granola", "rijstwafels", "ontbijtgranen", "melkpoeder", "suikerklontjes" },
        new string[] { "chips", "koek", "koekjes", "snoep", "chocolade", "drop", "nootjes", "popcorn", "stroopwafels", "stroopwafel", "crackers", "toastjes", "zoutjes", "borrelnootjes", "pinda's", "pinda", "kauwgom", "pepermunt", "repen", "reep", "biscuit", "biscuits", "tompouce", "gebak", "taart", "muffins", "wafels", "chocoladereep" },
        new string[] { "water", "cola", "fris", "sap", "jus", "bier", "wijn", "limonade", "ranja", "energy", "sportdrank", "frisdrank", "ijsthee", "energydrink", "spa", "sinas", "cassis", "tonic", "radler", "prosecco", "smoothie", "siroop" },
        new string[] { "ijs", "diepvries", "pizza", "friet", "patat", "doperwten", "spinazie à la crème", "vissticks", "ijsblokjes", "frikandellen", "kroketten", "bitterballen", "loempia", "loempia's", "kipnuggets", "magnum", "ijsjes" },
        new string[] { "shampoo", "tandpasta", "tandenborstel", "deo", "deodorant", "zeep", "douchegel", "scheermesjes", "maandverband", "tampons", "zonnebrand", "paracetamol", "pleisters", "wattenstaafjes", "mondwater", "babyolie", "bodylotion", "crème", "gezichtscrème", "conditioner", "haargel", "scheerschuim", "wattenschijfjes", "luiers", "billendoekjes", "ibuprofen", "lenzenvloeistof", "flosdraad", "lippenbalsem", "nagellak" },
        new string[] { "wc-papier", "toiletpapier", "keukenrol", "afwasmiddel", "wasmiddel", "vuilniszakken", "sponsjes", "allesreiniger", "batterijen", "aluminiumfolie", "vaatwastabletten", "wasverzachter", "wc papier", "keukenpapier", "vershoudfolie", "bakpapier", "wc-blokjes", "wc-eend", "schoonmaakazijn", "glasreiniger", "afwasborstel", "theedoeken", "kattenvoer", "hondenvoer", "kattenbakvulling", "lampen", "kaarsen", "lucifers", "vriezerzakjes", "boterhamzakjes" },
        new string[] {  },
    };
}
