"""Maakt de Engelse String Catalogs uit één woordenboek. python scripts/vertalingen.py

Sleutels komen uit `xcodebuild -exportLocalizations` (workflow teksten.yml). Nieuwe tekst in de app?
Draai die workflow, voeg de ontbrekende sleutels hieronder toe en draai dit script opnieuw.
"""
import json
import pathlib

EN = {
    "%@ %lldm": "%1$@ %2$lldm", "%@ = %lld": "%1$@ = %2$lld", "%@ betaalde · voor %@": "%1$@ paid · for %2$@",
    "%@ cm": "%@ cm", "%@ stemt": "%@ is voting", "%@ → %@": "%1$@ → %2$@", "%@, tik om te verwijderen": "%@, tap to remove",
    "%@°": "%@°", "%lld": "%lld", "%lld %@": "%1$lld %2$@", "%lld graden scheef": "%lld degrees off", "%lld minuten": "%lld minutes",
    "%lld personen": "%lld people", "%lld personen · %@": "%1$lld people · %2$@", "%lld teams": "%lld teams",
    "%lld van 5 sterren": "%lld of 5 stars", "%lld × ja": "%lld × yes", "%lld%%": "%lld%%", "%lld/5": "%lld/5", "0,00": "0.00",
    "Aan de slag": "Get started", "Afgevinkt": "Checked", "Afrekenen": "Settle up", "Afvinklijstje": "Checklist",
    "Afvinklijstje toevoegen": "Add checklist",
    "Alles belandt vanzelf in het juiste bakje. Twijfelt Kniv, dan vraagt hij het even.":
        "Everything lands in the right tray by itself. When Kniv isn't sure, it just asks.",
    "Alles staat op n.v.t., dus er valt niks te berekenen.": "Everything is set to N/A, so there's nothing to calculate.",
    "Ander": "Other", "Andere bon scannen": "Scan another receipt", "Annuleer": "Cancel", "Bakje": "Tray",
    "Bedrag in %@": "Amount in %@", "Betaald door": "Paid by", "Betaalverzoek": "Payment request", "Bewaar": "Save",
    "Bewaard": "Saved", "Bon lezen…": "Reading receipt…", "Camera niet beschikbaar": "Camera unavailable",
    "Countdown": "Countdown", "Countdowns": "Countdowns", "Dag": "Day", "Datum": "Date",
    "De screenshot staat straks op je klembord. Plak hem in het issue.": "The screenshot will be on your clipboard. Paste it into the issue.",
    "Deel PDF": "Share PDF", "Deel verdeling": "Share split", "Delen": "Split", "Dobbelstenen": "Dice", "Draai": "Spin",
    "Drinken": "Drinks", "Druk": "Busy",
    "Een potje houdt bij wie wat voorschoot, bijvoorbeeld op vakantie.": "A pot keeps track of who paid for what, for example on holiday.",
    "Eén zakmes": "One pocket knife", "En de winnaar is…": "And the winner is…", "Er stond niks in.": "There was nothing in it.",
    "Eten": "Food", "Even checken": "Quick check", "Focus": "Focus", "Focus deze week": "Focus this week", "Fooi": "Tip",
    "Foto kiezen": "Choose photo", "Foto maken": "Take photo", "Foto, tik om te vergroten": "Photo, tap to enlarge",
    "Fout melden": "Report a bug", "Geef Kniv toegang tot de camera in Instellingen.": "Give Kniv access to the camera in Settings.",
    "Geen AR op dit toestel": "No AR on this device", "Geen fooi": "No tip", "Geen herinnering": "No reminder",
    "Gesprek": "Conversation", "Gooi": "Roll", "Heel stil": "Very quiet", "Herinner me op deze plek": "Remind me at this place",
    "Herinneren %@?": "Remind %@?", "Houd je telefoon tegen de rand": "Hold your phone against the edge",
    "Huidige plek is School": "Current place is School", "Huidige plek is Thuis": "Current place is Home",
    "IBAN wijzigen": "Change IBAN", "Iedereen staat quitte.": "Everyone is square.", "Ik luister…": "Listening…",
    "Inspreken": "Dictate", "Inspreken in Kniv": "Dictate in Kniv", "Instellingen": "Settings", "JA": "YES", "Ja": "Yes",
    "Je bent bij de supermarkt": "You're at the supermarket", "Jouw IBAN": "Your IBAN", "Kies uit dit lijstje": "Pick from this list",
    "Kiezen": "Choose", "Klaar": "Done", "Kniv": "Kniv", "Kniv herinnert je hier": "Kniv will remind you here",
    "Kniv ruimt op": "Kniv tidies up", "Komt binnenkort": "Coming soon", "Kop": "Heads", "Kopieer": "Copy",
    "Leg alles vast": "Capture everything", "Leg je telefoon op het oppervlak": "Lay your phone on the surface",
    "Legt tekst vast in Kniv en sorteert hem in het juiste bakje.": "Captures text in Kniv and sorts it into the right tray.",
    "Lijstje": "List", "Locatie niet gevonden": "Location not found", "Luid, pas op je oren": "Loud, mind your ears",
    "Maak": "Create", "Meld": "Report", "Melding bij de supermarkt": "Notify at the supermarket",
    "Met het slotje open je een bakje alleen met Face ID. Eigen bakjes herkent Kniv zodra je hun naam gebruikt, en leert hij van jouw keuzes.":
        "With the lock, a tray only opens with Face ID. Kniv recognises your own trays as soon as you use their name, and learns from your choices.",
    "Meten": "Measure", "Mijn bakjes": "My trays", "Minuten": "Minutes", "Misschien bedoel je": "Maybe you mean", "Munt": "Tails",
    "N.v.t.": "N/A", "NEE": "NO", "Naam": "Name", "Naam toevoegen": "Add name", "Naam, bijv. Barcelona": "Name, e.g. Barcelona",
    "Nee": "No", "Niet vergrendeld": "Not locked", "Nieuw": "New", "Nieuw bakje": "New tray", "Nieuw in Kniv": "New in Kniv",
    "Nieuw item": "New item", "Nieuw potje": "New pot", "Nieuwe countdown": "New countdown", "Nieuwe stemming": "New vote",
    "Nieuwe timer": "New timer", "Nog %lld minuten": "%lld minutes left",
    "Nog geen idee wat ik hiermee moet. Probeer bijvoorbeeld \"12 oz\" of \"20 gbp\".": "Not sure what to do with this yet. Try \"12 oz\" or \"20 gbp\".",
    "Nog geen potjes": "No pots yet", "Nog geen timers. Tik op + voor pasta, thee of de was.": "No timers yet. Tap + for pasta, tea or the laundry.",
    "Nog niet gesorteerd": "Not sorted yet", "Nog niks vastgelegd": "Nothing captured yet", "Normale fooi: %@%%": "Usual tip: %@%%",
    "Notitie": "Note", "Onderdeel": "Section", "Oorverdovend": "Deafening", "Op naam van": "Account holder", "Op school": "At school",
    "Open": "Open", "Open met Face ID": "Open with Face ID",
    "Opent Kniv en begint meteen met luisteren. Handig op de Actieknop.": "Opens Kniv and starts listening right away. Handy on the Action button.",
    "Opent het mesje": "Opens the blade", "Opnieuw": "Reset", "Optie toevoegen": "Add option", "Pauze": "Pause",
    "Per persoon": "Per person", "Plekken": "Places", "Prijs zonder fooi": "Price without tip",
    "Prijskaartje fotograferen": "Photograph price tag", "Probeer": "Try", "Punt": "Point", "QR": "QR",
    "QR-code voor de bankapp": "QR code for your banking app", "Rad van fortuin": "Wheel of fortune",
    "Rechts = ja, links = nee": "Right = yes, left = no", "Richt het kruisje op het beginpunt": "Aim the crosshair at the start point",
    "Richt op een QR-code of streepjescode": "Point at a QR code or barcode", "Richt op het eindpunt en tik op +": "Aim at the end point and tap +",
    "Rustig": "Calm", "Scan een bon": "Scan a receipt", "Scan een document": "Scan a document", "Scan met je bankapp": "Scan with your banking app",
    "Scanner": "Scanner", "Schatting via de microfoon, geen geijkte meter.": "Estimate via the microphone, not a calibrated meter.",
    "School": "School", "Schud of tik om te gooien": "Shake or tap to roll",
    "Schudden om een fout te melden staat aan": "Shake to report a bug is on", "Service": "Service", "Sluiten": "Close",
    "Splitten": "Split", "Splitten met deze bon": "Split this receipt", "Staat erin!": "Got it!", "Staat erin, bij %@!": "Got it, in %@!",
    "Start": "Start", "Start een focusronde van 25 minuten.": "Start a 25-minute focus round.", "Start focus": "Start focus",
    "Start focus in Kniv": "Start focus in Kniv", "Start stemming": "Start vote", "Stop": "Stop", "Stop met inspreken": "Stop dictating",
    "Stuur verzoek": "Send request", "Team %lld": "Team %lld", "Tekst uit de foto": "Text from the photo",
    "Tel af naar een deadline, festival of vakantie.": "Count down to a deadline, festival or holiday.", "Thuis": "Home",
    "Thuis zie je je to-do's, op school je schoolnotities, bij de supermarkt je boodschappen. Alleen als er sinds de vorige keer iets nieuws is.":
        "At home you see your to-dos, at school your school notes, at the supermarket your groceries. Only when something is new since last time.",
    "Tik aan wie wat had": "Tap who had what", "Tik om af te vinken": "Tap to check off", "Tik om ongedaan te maken": "Tap to undo",
    "Tik op tekst om hem te kopiëren": "Tap text to copy it", "Timer": "Timer", "Timer loopt": "Timer running",
    "Timer: %@, %@": "Timer: %1$@, %2$@", "Timers": "Timers", "Toch meetellen": "Count it after all", "Top!": "Great!",
    "Totaal %@, mooi afgerond": "Total %@, nicely rounded", "Totaalbedrag": "Total amount", "Trillingen": "Haptics",
    "Typ iets om om te zetten": "Type something to convert",
    "Typ, spreek in of maak een foto. Kniv sorteert het voor je.": "Type, dictate or take a photo. Kniv sorts it for you.",
    "Typ, spreek in of maak een foto. Ook met de Actieknop of Siri.": "Type, dictate or take a photo. Also with the Action button or Siri.",
    "Uitgave": "Expense", "Uitgaven": "Expenses", "Valuta": "Currency", "Vandaag %lld rondes": "Today %lld rounds",
    "Vandaag!": "Today!", "Vastleggen": "Capture", "Verdeel": "Split up", "Verder": "Resume", "Vergrendeld met Face ID": "Locked with Face ID",
    "Versie": "Version", "Versie %@": "Version %@", "Verwijder": "Delete", "Verwijder notitie": "Delete note",
    "Vier handige mesjes in één app. Strak, snel en altijd bij de hand.": "Handy blades in one app. Clean, fast and always at hand.",
    "Voeg toe": "Add", "Volgende": "Next", "Voor wie": "For whom", "Voorbij": "Over", "Waar tel je naar af?": "What are you counting down to?",
    "Waarvoor?": "What for?", "Wat ging er mis?": "What went wrong?", "Wat wil je kwijt?": "What's on your mind?", "Waterpas": "Level",
    "Welkom thuis": "Welcome home", "Wie doen er mee? (komma's)": "Who's in? (commas)", "Wie stemmen er? (komma's)": "Who's voting? (commas)",
    "Wie waren er? (komma's)": "Who was there? (commas)", "Zet in Kniv": "Add to Kniv", "Zoek in alles": "Search everything",
    "dB": "dB", "dag": "day", "dagen": "days", "morgen": "tomorrow", "n.v.t.": "N/A", "niet van toepassing": "not applicable",
    "vandaag": "today", "≈ %@": "≈ %@", "1": "1",
    # widgets
    "Kniv vastleggen": "Kniv capture", "Leg iets vast": "Capture something",
    "Leg met één tik iets vast: typen, inspreken, foto of lijstje.": "Capture something in one tap: type, dictate, photo or list.",
    # niet door de export gevonden, wel zichtbaar via LocalizedStringKey(...)
    "Potjes": "Pots", "Bon": "Receipt", "Omzetten": "Convert", "Rad": "Wheel", "Dobbelen": "Dice",
    "Teams": "Teams", "Stemmen": "Vote", "QR-code": "QR code", "Document": "Document", "Tekst": "Text", "Liniaal": "Ruler",
    "Geluid": "Sound",
    "Garantie tot": "Warranty until",
    "Uit de kluis halen": "Remove from vault",
    "Bewaar in de garantiekluis": "Save in warranty vault",
    "Garantie": "Warranty",
    "De garantie op %@ loopt over een maand af. Nog iets mis mee?": "The warranty on %@ ends in a month. Anything wrong with it?",
    "Je hebt in Nederland minstens twee jaar recht op een product dat werkt. Kniv waarschuwt een maand voordat die tijd om is.": "In the Netherlands you're entitled to a working product for at least two years. Kniv warns you a month before that ends.",
    "Garantiekluis": "Warranty vault",
    "verlopen": "expired",
    "nog even": "almost over",
    "nog %lld mnd": "%lld mo left",
    "Je plek": "Your spot",
    "Je bent er!": "You're there!",
    "Vastgelegd %@": "Saved %@",
    "Plek vergeten": "Forget spot",
    "Kompas zoekt je locatie…": "Compass is finding you…",
    "Waar laat je iets achter?": "Where are you leaving something?",
    "Leg de plek van je fiets, auto of tent vast. Straks wijst een pijl je de weg terug.": "Save where your bike, car or tent is. Later an arrow points you back.",
    "Naam, bijv. Fiets": "Name, e.g. Bike",
    "Leg deze plek vast": "Save this spot",
    "Wifi": "Wi-Fi",
    "Tekst of link": "Text or link",
    "Soort": "Type",
    "Netwerknaam": "Network name",
    "Wachtwoord": "Password",
    "QR-code, tik om te vergroten": "QR code, tap to enlarge",
    "Laat je vrienden deze code scannen met hun camera.": "Let your friends scan this code with their camera.",
    "Tik om te vergroten.": "Tap to enlarge.",
    "Maak QR": "Make QR",
    "Terug": "Find back",
    "Omdraaien om te focussen": "Flip to focus",
    "Focus loopt. Pak je telefoon op om te pauzeren.": "Focus is on. Pick up your phone to pause.",
    "Leg je telefoon met het scherm op tafel en de focus start.": "Put your phone face down and focus starts.",
    "Even ademen": "Take a breath",
    "In": "In",
    "Vast": "Hold",
    "Uit": "Out",
    "Goed gedaan": "Well done",
    "Adem rustig mee": "Breathe along",
    "Begin": "Begin",
    "Duur": "Duration",
    "%lld min": "%lld min",
    "= %@": "= %@",
    "Zet het antwoord in je notitie": "Puts the answer in your note",
    "Van gisteren-jij": "From yesterday-you",
    "Gelezen": "Read",
    "Wat moet morgen-jij weten?": "What should tomorrow-you know?",
    "Niet nu": "Not now",
    "Bijvoorbeeld: laptoplader mee, om 9 uur presentatie": "For example: bring laptop charger, presentation at 9",
    "Leg klaar voor morgen": "Save for tomorrow",
    "Niet vergeten": "Don't forget",
    "Bewaar in Kniv": "Save to Kniv",
    "Er viel niks te bewaren.": "There was nothing to save.",
    "Bewaard in %@.": "Saved in %@.",
    "Bewaard in Kniv.": "Saved in Kniv.",
    "Kniv in je deelmenu": "Kniv in your share sheet",
    "Open Opdrachten": "Open Shortcuts",
    "Rustmodus 's avonds": "Quiet mode in the evening",
    "Vanaf %lld:00": "From %lld:00",
    "Tot %lld:00": "Until %lld:00",
    "In rustmodus is Kniv donker en rustig, en zwijgen de plekmeldingen.": "In quiet mode Kniv is dark and calm, and place notifications stay silent.",
    "Mijn week in Kniv": "My week in Kniv",
    "Deel je week": "Share your week",
    "Open Opdrachten → + → Voeg actie toe → Kniv → Bewaar in Kniv. Tik op ⓘ en zet **Toon in deelmenu** aan. Daarna staat Kniv onder Deel in elke app.": "Open Shortcuts → + → Add action → Kniv → Save to Kniv. Tap ⓘ and turn on **Show in Share Sheet**. Kniv then appears under Share in every app.",
    "Deel %@": "Share %@",
    "Wie meedoet logt in met Google en kan zelf uitgaven toevoegen. De link verloopt na 30 dagen.": "People who join sign in with Google and can add expenses themselves. The link expires after 30 days.",
    "Doe mee met ons potje in Kniv": "Join our pot in Kniv",
    "Deel potje": "Share pot",
    "Samen · %@": "Together · %@",
    "Wachten op anderen…": "Waiting for others…",
    "Kies mee in Kniv": "Pick together in Kniv",
    "Nodig uit": "Invite",
    "Stop samen kiezen": "Stop picking together",
    "Kies samen met vrienden": "Pick together with friends",
    "Doe mee": "Join",
    "Code van je vriend": "Your friend's code",
    "Start stemming voor iedereen": "Start vote for everyone",
    "Wachten tot iedereen gestemd heeft (%lld/%lld)": "Waiting for everyone to vote (%1$lld/%2$lld)",
    "Ik": "Me",
    "Vandaag": "Today",
    "Jouw week": "Your week",
    "gefocust": "focused",
    "vastgelegd": "captured",
    "in potjes": "in pots",
    "%lld boodschappen open": "%lld groceries left",
    "Je krijgt nog %@": "You're owed %@",
    "Je moet nog %@ betalen": "You still owe %@",
    "Groente & fruit": "Fruit & veg",
    "Brood": "Bread",
    "Vlees & vis": "Meat & fish",
    "Zuivel & eieren": "Dairy & eggs",
    "Kaas & beleg": "Cheese & spreads",
    "Pasta, rijst & blik": "Pasta, rice & tins",
    "Ontbijt & koffie": "Breakfast & coffee",
    "Koek, snoep & chips": "Biscuits, sweets & crisps",
    "Drinken": "Drinks",
    "Diepvries": "Frozen",
    "Verzorging": "Personal care",
    "Huishouden": "Household",
    "Overig": "Other",
    "Welkom bij Kniv": "Welcome to Kniv",
    "Log in om je notities ook op je laptop te zien en lijstjes met vrienden te delen.": "Log in to see your notes on your laptop too and share lists with friends.",
    "Inloggen met Google": "Sign in with Google",
    "Inloggen lukte niet. Probeer het nog eens.": "Signing in didn't work. Please try again.",
    "Deze uitnodiging is verlopen of onbekend.": "This invitation has expired or is unknown.",
    "Waar": "Where",
    "Alleen deze telefoon": "Only this phone",
    "Ook op mijn laptop": "Also on my laptop",
    "Gedeeld": "Shared",
    "Nodig iemand uit": "Invite someone",
    "Link om alleen te kijken": "View-only link",
    "Doe mee met mijn lijstje in Kniv": "Join my list in Kniv",
    "Wie meedoet logt in met Google. De links verlopen na 30 dagen.": "People who join sign in with Google. Links expire after 30 days.",
    "Account": "Account",
    "Ingelogd als": "Signed in as",
    "Uitloggen": "Sign out",
    "Account verwijderen": "Delete account",
    "Account en alles in de cloud verwijderen?": "Delete your account and everything in the cloud?",
    "Verwijder alles": "Delete everything",
    "Gedeelde lijstjes gaan over naar wie het langst meedoet.": "Shared lists pass to whoever has been in them longest.",
    "%lld nieuw van anderen": "%lld new from others", "Update beschikbaar": "Update available",
    "Versie %@. Tik om te installeren via SideStore.": "Version %@. Tap to install via SideStore.", "Typ": "Type", "Spreek": "Speak", "Foto": "Photo", "Lijst": "List",
}

SIRI = {"Inspreken in ${applicationName}": "Dictate in ${applicationName}",
        "Start focus in ${applicationName}": "Start focus in ${applicationName}",
        "Zet iets in ${applicationName}": "Add something to ${applicationName}"}

PLIST = {"CFBundleDisplayName": "Kniv", "CFBundleName": "Kniv",
         "NSCalendarsFullAccessUsageDescription": "Kniv checks your calendar to set a reminder at a free moment.",
         "NSCameraUsageDescription": "Kniv takes photos of notes, whiteboards and receipts.",
         "NSFaceIDUsageDescription": "Kniv opens locked trays with Face ID.",
         "NSLocationAlwaysAndWhenInUseUsageDescription": "Kniv shows your list at the supermarket, at school or at home, even when the app is closed.",
         "NSLocationWhenInUseUsageDescription": "Kniv saves a place so it can remind you there.",
         "NSMicrophoneUsageDescription": "Kniv only listens while you dictate.",
         "NSSpeechRecognitionUsageDescription": "Kniv transcribes your dictated notes, on your iPhone itself."}

WIDGET = {"Kniv", "Kniv vastleggen", "Leg iets vast", "Leg met één tik iets vast: typen, inspreken, foto of lijstje.",
          "Typ", "Spreek", "Foto", "Lijst"}


def catalogus(pad, vertaling, sleutels=None):
    items = {k: {"localizations": {"en": {"stringUnit": {"state": "translated", "value": v}}}}
             for k, v in vertaling.items() if sleutels is None or k in sleutels}
    pathlib.Path(pad).write_text(json.dumps({"sourceLanguage": "nl", "strings": items, "version": "1.0"},
                                            ensure_ascii=False, indent=2), encoding="utf-8")


if __name__ == "__main__":
    catalogus("Kniv/Localizable.xcstrings", EN)
    catalogus("Kniv/AppShortcuts.xcstrings", SIRI)
    catalogus("Kniv/InfoPlist.xcstrings", PLIST)
    catalogus("KnivWidgets/Localizable.xcstrings", EN, WIDGET)
    catalogus("KnivWidgets/InfoPlist.xcstrings", PLIST, {"CFBundleDisplayName", "CFBundleName"})
    print(f"{len(EN)} teksten vertaald")
